name: GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request: # Also trigger on pull requests for preview builds (optional, but good practice)

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Allows checking out the repository
  pages: write # Allows deploying to GitHub Pages
  id-token: write # Required for OIDC authentication with GitHub Pages

# Allow only one concurrent deployment, skipping runs queued between the start and latest queued.
# However, we only want to cancel workflow runs for the latest pushed commit.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job to build the project and upload the artifact
  build:
    runs-on: ubuntu-22.04 # Specify the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch submodules if your project uses them (e.g., Hugo themes)
          fetch-depth: 0 # Fetch all history for Git-related features (e.g., Hugo .GitInfo)

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify pnpm version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Specify Node.js version
          cache: "pnpm" # Enable caching for pnpm dependencies

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Install project dependencies

      - name: Build project
        run: pnpm run build # Run your project's build command (e.g., Vite build)

      - name: Upload production-ready assets
        uses: actions/upload-pages-artifact@v3 # Uploads the build output as an artifact
        with:
          path: ./dist # The directory containing your built static files

  # Job to deploy the uploaded artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages # Specifies the deployment environment (creates if not exists)
      url: ${{ steps.deployment.outputs.page_url }} # Sets the URL of the deployed page
    runs-on: ubuntu-22.04 # Specify the runner environment
    needs: build # This job depends on the 'build' job completing successfully

    steps:
      - name: Deploy to GitHub Pages
        id: deployment # Assigns an ID to this step for accessing its outputs
        uses: actions/deploy-pages@v4 # The official GitHub Pages deployment action